"""Phase 6: upload trained checkpoints to HuggingFace Hub with model cards.

For each policy, creates a public repo at ``adimunot21/<policy>-pusht-lab``
and uploads the ``pretrained_model/`` directory plus a generated model card
(README.md) describing training config, dataset, eval results, and a runnable
load+infer snippet.

Why we don't use LeRobot's built-in ``push_to_hub`` flag during training:
  - We want to publish a CURATED checkpoint (the one with best eval), not the
    last one which is often slightly worse than an earlier one.
  - The model card needs to reference Phase 5 eval results which don't exist
    until after training finishes.
  - Auto-publishing during training risks pushing partial checkpoints if the
    process crashes.

Authentication: requires ``HF_TOKEN`` in the environment (or in ``.env``).
Get one at https://huggingface.co/settings/tokens (write scope).
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from huggingface_hub import HfApi

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Model card generation
# ---------------------------------------------------------------------------


_MODEL_CARD_TEMPLATE = """---
library_name: lerobot
tags:
- robotics
- pusht
- imitation-learning
- {policy_type}
license: apache-2.0
datasets:
- lerobot/pusht
metrics:
- success_rate
- avg_max_reward
model-index:
- name: {repo_name}
  results:
  - task:
      type: imitation-learning
      name: PushT
    dataset:
      type: lerobot/pusht
      name: PushT
    metrics:
    - type: success_rate
      value: {success_rate_pct:.1f}
      name: Success rate (max overlap >= 0.95)
    - type: avg_max_reward
      value: {avg_max_reward:.4f}
      name: Average max reward (block-target overlap)
---

# {policy_name} on PushT

{policy_class_name} trained on `lerobot/pusht`, part of the
[lerobot-pusht-lab](https://github.com/adimunot21/lerobot-pusht-lab) project —
a sim-based imitation learning lab to build fluency with the LeRobot stack
before SO-101 hardware arrives.

## Eval results

| Metric | Value |
|---|---|
| **Success rate (95% CI)** | **{success_rate_pct:.1f}%** [{success_ci_low_pct:.1f}%, {success_ci_high_pct:.1f}%] |
| Avg max_reward | {avg_max_reward:.4f} |
| Avg sum_reward | {avg_sum_reward:.4f} |
| Avg episode length | {avg_episode_length:.1f} steps |
| Eval episodes | {n_episodes} |
| Success threshold | max_reward >= {success_threshold:.2f} |

Comparison with other policies trained on the same dataset and compute budget
is in the project repo: [outputs/comparison/comparison.md](https://github.com/adimunot21/lerobot-pusht-lab/blob/main/outputs/comparison/comparison.md).

## Training config

| Hyperparameter | Value |
|---|---|
{config_table}

## Hardware constraints

Trained on a single **NVIDIA GTX 1650 (4 GB VRAM)** — the binding constraint
for hyperparameter choices. See the project repo for the VRAM-fitting compromise
process documented in `PLAN.md`.

## How to load and run

```python
from lerobot.policies.factory import make_policy
from lerobot.policies.{policy_module}.modeling_{policy_module} import {policy_class_name}

policy = {policy_class_name}.from_pretrained("{repo_id}")
policy.eval()
# See lerobot/scripts/lerobot_eval.py for the full rollout pattern.
```

## Project context

This is one of three policies trained on the same dataset for comparison:

- **Diffusion Policy** — multimodal action distribution via DDPM
- **ACT** (Action Chunking Transformer) — multimodal via CVAE
- **MLP-BC** (from-scratch baseline) — single-step MSE; expected to fail on
  PushT due to mode-averaging on multimodal expert demos

Generated by [lerobot-pusht-lab](https://github.com/adimunot21/lerobot-pusht-lab).
"""


def build_model_card(
    *,
    repo_id: str,
    policy_type: str,
    policy_class_name: str,
    policy_module: str,
    train_config: dict[str, Any],
    eval_metrics: dict[str, Any],
) -> str:
    """Render the model card markdown.

    `train_config` should be the dict from train_config.json; `eval_metrics`
    is the dict from EvalMetrics.to_dict(). Missing fields fall back to "?"
    so the card is still serviceable for partial data.
    """
    repo_name = repo_id.split("/")[-1]
    policy_name = repo_name.replace("-", " ").title()

    # Pull the most-justified training hyperparameters into a small table.
    # We avoid dumping the entire train_config — it has 60+ fields, most boring.
    notable_keys = [
        ("Batch size", train_config.get("batch_size", "?")),
        ("Steps", train_config.get("steps", "?")),
        ("Optimizer LR", train_config.get("policy", {}).get("optimizer_lr", "?")),
        ("Seed", train_config.get("seed", "?")),
        ("AMP", train_config.get("policy", {}).get("use_amp", "?")),
        ("Vision backbone", train_config.get("policy", {}).get("vision_backbone", "?")),
    ]
    config_table = "\n".join(f"| {k} | `{v}` |" for k, v in notable_keys)

    return _MODEL_CARD_TEMPLATE.format(
        repo_id=repo_id,
        repo_name=repo_name,
        policy_name=policy_name,
        policy_type=policy_type,
        policy_class_name=policy_class_name,
        policy_module=policy_module,
        config_table=config_table,
        success_rate_pct=100 * eval_metrics.get("success_rate", 0.0),
        success_ci_low_pct=100 * eval_metrics.get("success_ci_low", 0.0),
        success_ci_high_pct=100 * eval_metrics.get("success_ci_high", 0.0),
        avg_max_reward=eval_metrics.get("avg_max_reward", 0.0),
        avg_sum_reward=eval_metrics.get("avg_sum_reward", 0.0),
        avg_episode_length=eval_metrics.get("avg_episode_length", 0.0),
        n_episodes=eval_metrics.get("n_episodes", 0),
        success_threshold=eval_metrics.get("success_threshold", 0.95),
    )


# ---------------------------------------------------------------------------
# Upload
# ---------------------------------------------------------------------------


# Map our internal policy types to the LeRobot module names used in import lines.
_POLICY_TYPE_TO_LEROBOT_MODULE = {
    "diffusion": ("diffusion", "DiffusionPolicy"),
    "act":       ("act", "ACTPolicy"),
    # MLP-BC is our own — model card uses our package's import path
    "mlp_bc":    ("mlp_bc", "MLPBC"),  # not a real lerobot module — overridden in the card
}


@dataclass
class UploadSpec:
    """One upload job. The caller assembles a list of these and runs publish_all()."""

    pretrained_model_dir: Path
    eval_metrics_path: Path
    train_config_path: Path
    repo_id: str          # e.g. "adimunot21/diffusion-pusht-lab"
    policy_type: str      # 'diffusion', 'act', 'mlp_bc'
    private: bool = False


def publish(spec: UploadSpec, token: str | None = None, dry_run: bool = False) -> str:
    """Create the repo (if needed), generate the model card, upload everything.

    Returns the repo URL.

    ``dry_run=True`` writes the model card to a temp file but skips Hub calls —
    useful for verifying the card looks right before publishing for real.
    """
    api = HfApi(token=token)

    # Validate inputs early
    if not spec.pretrained_model_dir.is_dir():
        raise FileNotFoundError(f"pretrained_model_dir not found: {spec.pretrained_model_dir}")
    if not spec.eval_metrics_path.is_file():
        raise FileNotFoundError(f"eval_metrics not found: {spec.eval_metrics_path}")
    if not spec.train_config_path.is_file():
        raise FileNotFoundError(f"train_config not found: {spec.train_config_path}")

    train_config = json.loads(spec.train_config_path.read_text())
    eval_metrics = json.loads(spec.eval_metrics_path.read_text())

    policy_module, policy_class_name = _POLICY_TYPE_TO_LEROBOT_MODULE.get(
        spec.policy_type, (spec.policy_type, spec.policy_type.upper())
    )

    card = build_model_card(
        repo_id=spec.repo_id,
        policy_type=spec.policy_type,
        policy_class_name=policy_class_name,
        policy_module=policy_module,
        train_config=train_config,
        eval_metrics=eval_metrics,
    )

    # Write the card into the upload dir as README.md
    readme_path = spec.pretrained_model_dir / "README.md"
    readme_path.write_text(card)
    logger.info("wrote model card: %s", readme_path)

    if dry_run:
        logger.info("[dry_run] skipping create_repo + upload_folder for %s", spec.repo_id)
        return f"https://huggingface.co/{spec.repo_id}"

    logger.info("create_repo: %s (private=%s)", spec.repo_id, spec.private)
    api.create_repo(repo_id=spec.repo_id, private=spec.private, exist_ok=True)
    logger.info("upload_folder: %s → %s", spec.pretrained_model_dir, spec.repo_id)
    commit = api.upload_folder(
        repo_id=spec.repo_id,
        folder_path=str(spec.pretrained_model_dir),
        commit_message=f"Add {spec.policy_type} checkpoint trained on lerobot/pusht",
        # Don't upload eval JSON / wandb artifacts — they go in the project repo
        ignore_patterns=["*.log", "wandb/*", "training_state/*", "__pycache__/*"],
    )
    url = f"https://huggingface.co/{spec.repo_id}"
    logger.info("published: %s (commit %s)", url, commit.oid[:8] if hasattr(commit, "oid") else "?")
    return url


# ---------------------------------------------------------------------------
# Smoke (model card rendering only — no Hub calls)
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    """Render a fake model card to verify the template fills correctly."""
    fake_train = {
        "batch_size": 64,
        "steps": 200000,
        "seed": 1000,
        "policy": {
            "optimizer_lr": 1e-4,
            "use_amp": True,
            "vision_backbone": "resnet18",
        },
    }
    fake_eval = {
        "success_rate": 0.62,
        "success_ci_low": 0.48,
        "success_ci_high": 0.74,
        "avg_max_reward": 0.85,
        "avg_sum_reward": 95.3,
        "avg_episode_length": 200.0,
        "n_episodes": 50,
        "success_threshold": 0.95,
    }
    card = build_model_card(
        repo_id="adimunot21/diffusion-pusht-lab",
        policy_type="diffusion",
        policy_class_name="DiffusionPolicy",
        policy_module="diffusion",
        train_config=fake_train,
        eval_metrics=fake_eval,
    )
    print(card[:1500])
    print("...")
    print()
    print("smoke test PASSED")
