#!/usr/bin/env python
"""Phase 5 final deliverable: cross-policy comparison report from eval JSONs.

Takes the eval_metrics.json files written by ``eval_mlp_bc.py`` (and the
LeRobot-eval JSON outputs once we wire those up), produces a markdown report
+ two plots in ``outputs/comparison/``.

Pure post-processing — never re-runs evals. Cheap to iterate on the report
formatting without touching the GPU.

Usage::

    # Default: discover all eval JSONs under outputs/eval/<policy>/eval_metrics.json
    python scripts/compare_policies.py

    # Or explicit list:
    python scripts/compare_policies.py \\
        outputs/eval/diffusion_pusht/eval_metrics.json \\
        outputs/eval/act_pusht/eval_metrics.json \\
        outputs/eval/mlp_bc_pusht/eval_metrics.json
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime
from pathlib import Path

from lerobot_pusht_lab.eval.compare import load_eval_metrics, write_full_comparison


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument(
        "metric_files",
        nargs="*",
        type=Path,
        help="Paths to eval_metrics.json files. If empty, discovers all under outputs/eval/.",
    )
    p.add_argument(
        "--eval-dir",
        type=Path,
        default=Path("outputs/eval"),
        help="Where to look for eval_metrics.json (only used when no positional args).",
    )
    p.add_argument(
        "--output-dir",
        type=Path,
        default=Path("outputs/comparison"),
        help="Where to write comparison.md and plots.",
    )
    p.add_argument(
        "--title",
        default="PushT — Diffusion Policy vs ACT vs MLP-BC",
    )
    p.add_argument("-v", "--verbose", action="store_true")
    return p.parse_args()


def discover_metric_files(eval_dir: Path) -> list[Path]:
    """Find all ``<policy>/eval_metrics.json`` files under ``eval_dir``."""
    return sorted(eval_dir.glob("*/eval_metrics.json"))


def main() -> int:
    args = parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(name)s] %(message)s",
        datefmt="%H:%M:%S",
    )
    logger = logging.getLogger("compare_policies")

    files = list(args.metric_files) or discover_metric_files(args.eval_dir)
    if not files:
        logger.error("no eval_metrics.json files found under %s", args.eval_dir)
        logger.error("run evals first (e.g. `python scripts/eval_mlp_bc.py`)")
        return 1

    logger.info("loading %d eval result(s):", len(files))
    metrics = []
    for f in files:
        if not f.exists():
            logger.warning("  skipping (missing): %s", f)
            continue
        m = load_eval_metrics(f)
        logger.info("  %s → %s (%d episodes, %.1f%% success)",
                    f, m.policy_name, m.n_episodes, 100 * m.success_rate)
        metrics.append(m)

    if not metrics:
        logger.error("no valid eval results loaded")
        return 1

    notes = (
        f"_Generated: {datetime.now().isoformat(timespec='seconds')}_  \n"
        f"_Generated by: `scripts/compare_policies.py`_\n"
    )
    outs = write_full_comparison(metrics, args.output_dir, title=args.title, notes=notes)
    logger.info("wrote: %s", outs.report_md)
    logger.info("wrote: %s", outs.success_plot)
    logger.info("wrote: %s", outs.distribution_plot)
    return 0


if __name__ == "__main__":
    sys.exit(main())
